# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_tag',
            name='TagID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='t_url',
            name='URLID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
